# Generated by Django 4.1.2 on 2022-10-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiscoSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('serial', models.CharField(blank=True, max_length=150, null=True)),
                ('version', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CiscoSwitchs',
            },
        ),
        migrations.CreateModel(
            name='Fortigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('serial', models.CharField(blank=True, max_length=150, null=True)),
                ('version', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Firewalls',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SystemUsers',
            },
        ),
        migrations.CreateModel(
            name='FortigateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fortigate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewallconfig', to='networks.fortigate')),
            ],
            options={
                'db_table': 'FortigateConfigs',
            },
        ),
        migrations.AddField(
            model_name='fortigate',
            name='systemuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall', to='networks.systemuser'),
        ),
        migrations.CreateModel(
            name='CiscoSwitchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ciscoswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciscoswitchconfig', to='networks.ciscoswitch')),
            ],
            options={
                'db_table': 'CiscoSwitchConfigs',
            },
        ),
        migrations.AddField(
            model_name='ciscoswitch',
            name='systemuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciscoswitch', to='networks.systemuser'),
        ),
    ]
