# Generated by Django 4.1.2 on 2022-10-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_arubaswitch_arubaswitchconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='HpSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('serial', models.CharField(blank=True, max_length=150, null=True)),
                ('version', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('systemuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpswitch', to='networks.systemuser')),
            ],
            options={
                'db_table': 'HpSwitch',
            },
        ),
        migrations.CreateModel(
            name='HpSwitchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hpswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpswitchconfig', to='networks.hpswitch')),
            ],
            options={
                'db_table': 'HpSwitchConfigs',
            },
        ),
    ]
