# Generated by Django 4.1.2 on 2022-10-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_hpswitch_hpswitchconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DellSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('serial', models.CharField(blank=True, max_length=150, null=True)),
                ('version', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('systemuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dellswitch', to='networks.systemuser')),
            ],
            options={
                'db_table': 'DellSwitch',
            },
        ),
        migrations.CreateModel(
            name='DellSwitchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dellswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dellswitchconfig', to='networks.dellswitch')),
            ],
            options={
                'db_table': 'DellSwitchConfigs',
            },
        ),
    ]
