# Generated by Django 4.1.2 on 2022-10-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_dellswitch_dellswitchconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtremeSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150, null=True)),
                ('model', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('serial', models.CharField(blank=True, max_length=150, null=True)),
                ('version', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('systemuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extremeswitch', to='networks.systemuser')),
            ],
            options={
                'db_table': 'ExtremeSwitch',
            },
        ),
        migrations.CreateModel(
            name='ExtremeSwitchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('extremeswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extremeswitchconfig', to='networks.extremeswitch')),
            ],
            options={
                'db_table': 'ExtremeSwitchConfigs',
            },
        ),
    ]
